runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: build/es6-bundled/bower_components
  secure: always

- url: /img
  static_dir: build/es6-bundled/img
  secure: always

- url: /src
  static_dir: build/es6-bundled/src
  secure: always

- url: /manifest.json
  static_files: build/es6-bundled/manifest.json
  upload: build/es5-bundled/manifest.json
  secure: always

- url: /.*
  static_files: build/es6-bundled/index.html
  upload: build/es5-bundled/index.html
  secure: always